CFLAGS := -pipe -Wall -Werror \
          -O3 -ffast-math \
          #-march=corei7 -mfpmath=sse -msse4.2 -mno-ssse3 \

%.o: %.c *.h Makefile.gcc
	$(CC) -c $(CFLAGS) $<

libnile.a: nile.o
	$(AR) rcs $@ $^

clean:
	$(RM) *.o *.a
