CFLAGS = /nologo /TP /EHsc /GR- \
         /W3 /wd4244 /wd4141 \
         /fp:fast /arch:SSE2 /O2 /Oi

libnile.lib: nile.obj
	lib /nologo /OUT:libnile.lib nile.obj

nile.obj: *.h *.c
	cl $(CFLAGS) /c nile.c

clean:
	del *.obj *.lib
