TARGET  := $(shell $(CC) -dumpmachine)
LDFLAGS := -L.. -lnile
CFLAGS  := -pipe -Wall -Werror -I.. \
           -O3 -ffast-math

ifneq (,$(findstring mingw,$(TARGET))$(findstring cygwin,$(TARGET)))
  LDFLAGS += # TODO windows
else
  LDFLAGS += -lm -pthread
endif

%-test: %-test.c FORCE
	$(MAKE) -C .. -f Makefile.gcc
	$(CC) $< -o $@ $(CFLAGS) $(LDFLAGS)

clean:
	$(RM) -r *-test *.dSYM

FORCE:
